### ISSUE TITLE
Back button does not work on the garden page (major bug)

### ISSUE THREAD

**Issue by jm278** [info442-su23/b-team#71]
Major bug 
When I'm on the garden page the back button is not functional. 
Tested on macOS Catalina 
Steps to reproduce: visit the garden page
Expected result: on click of the back button, I expected to go back to the previous page 
actual result: nothing happened 

<img width="1133" alt="Screenshot 2023-08-08 at 5 29 51 PM" src="https://github.com/info442-su23/b-team/assets/81663021/15226550-af3a-4b7b-b7db-71bc277a696d">

**Comment by sloaneshea** [comment]
https://github.com/info442-su23/b-team/issues/67#issue-1842266233
