### ISSUE TITLE
Bug  major - sort game sudden stop

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/b-team#72]
When I select an answer and submit it for the sort game, I am directed to a blank green screen with no options. On closer inspection, the url is always incorrect sort until I choose glass and bottles, which shouldn't be correnct for cucumber?

Expect: Cucumber to be compost, and for the game to continue onto the next item

![image](https://github.com/info442-su23/b-team/assets/114948475/39e8ed0b-aeeb-4602-a21c-899347e04ad5)
![image](https://github.com/info442-su23/b-team/assets/114948475/bd810313-47ec-4ab8-8ee7-fa960c48be63)
![image](https://github.com/info442-su23/b-team/assets/114948475/0e0c6331-9b52-4ff3-a36d-ff4fd9f7cf8e)

**Comment by VictoriaVVei** [comment]
![image](https://github.com/info442-su23/b-team/assets/91993339/ce9f4294-9907-4ef3-a10e-b11a07b40004)
error

**Comment by BrookePedersen** [comment]
how to fix: link incorrect and correct pages, and score page

**Comment by bonglrob** [comment]
resolved in [9f6fa93](https://github.com/info442-su23/b-team/commit/9f6fa93eec9c914aaec39b68411ed8739604734e)
