### ISSUE TITLE
Score Card (minor Bug)

### ISSUE THREAD

**Issue by atimch** [info442-su23/b-team#73]
On the quiz I chose 5 answers that were all incorrect and the score listed 5/5 correct in the end. Expected result to be 0/5.

Firefox

**Comment by BrookePedersen** [comment]
how to fix: update the written text score after completing the quiz.

**Comment by wphan-1925132** [comment]
[commit bf143bfbc26c908109c4402ee017632124cea7b6](https://github.com/info442-su23/b-team/commit/bf143bfbc26c908109c4402ee017632124cea7b6#diff-fdca1cb1e8a463f8cc8be935acd5b9451da4e190ae36116bdd770cae4e936ceb)
