### ISSUE TITLE
Bug major - can't plant seeds beyond tomato

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/b-team#74]
After I grew my tomato seed, I'm unable to click on the pepper seed to continue using your app or earn points from quests/games

Expect: To be able to grow the pepper plant and save my progress

![image](https://github.com/info442-su23/b-team/assets/114948475/8ca07d03-941f-4e93-8e09-3cde661b885d)

**Comment by BrookePedersen** [comment]
how to fix: further develop the game past first seed.
