### ISSUE TITLE
Games Feature Not Working Properly; Severity: Major

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/b-team#75]
Summary: The app is intended to use the `Games` feature to earn Energy Points. However, after selecting the answer and hit `submit`, it takes me to a blank page. And there is no way to go back, so I just got stuck.
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Introduction -> Select Seed -> Games -> Sort -> Start -> Choice + Submit -> Blank Page
Expected Result: Take me to the next question
Actual Result: Blank Page

**Comment by sloaneshea** [comment]
https://github.com/info442-su23/b-team/issues/72#issue-1842275017
