### ISSUE TITLE
Add Written Instructions to DIY - Feature Request

### ISSUE THREAD

**Issue by taylor-russon** [info442-su23/b-team#80]
Even though you state all the materials at the beginning of the compost DIY, as I follow the steps I am not sure what is happening in each picture. It could be helpful to add a little bit of text to describe what each picture is showing.

**Comment by BrookePedersen** [comment]
not at the top of our priority list, just an added bonus to the app.

**Comment by bonglrob** [comment]
resolved in e47d3e0
