### ISSUE TITLE
Nav Bar Doesn't Work on Garden Page - Bug Major

### ISSUE THREAD

**Issue by elisabeth-h7** [info442-su23/b-team#81]
The navigation bar is not functional when you get to the garden page. 

Mac OS Catalina, Chrome

Steps to reproduce:
- Navigate to garden page from games
- Try to click the navigation links at the top of the page

Expected:
- to be brought to different pages on the site

Received:
- buttons were not clickable

**Comment by sloaneshea** [comment]
https://github.com/info442-su23/b-team/issues/67#issue-1842266233
