### ISSUE TITLE
Sort Game Doesn't Work - Bug Major

### ISSUE THREAD

**Issue by elisabeth-h7** [info442-su23/b-team#82]
When playing the sort game, if you put a wrong answer it brings you to a blank green page. 

Mac OS Catalina, Chrome

Steps to reproduce:
- go to games
- go to sort 
- click compost for the first question and submit 

Expected:
- an incorrect/correct screen

Received: 
- a blank green page

<img width="1429" alt="Screen Shot 2023-08-08 at 5 58 49 PM" src="https://github.com/info442-su23/b-team/assets/62919487/18ac1c14-a532-4d86-b8ba-2a49445b616b">

**Comment by sloaneshea** [comment]
https://github.com/info442-su23/b-team/issues/72#issue-1842275017
