### ISSUE TITLE
Garden Page introduction

### ISSUE THREAD

**Issue by siyuanji1** [info442-su23/b-team#83]
Provide an introduction on the Garden page, instead of just displaying the message "your garden is empty." Offer some explanation about the purpose of this page or give directions on what I should click to achieve some results. The guidance can enhance the user's understanding and engagement with the page. Moreover, show how to add to my garden.
<img width="1123" alt="截屏2023-08-08 下午6 00 01" src="https://github.com/info442-su23/b-team/assets/114948473/9e9dd896-0dbd-4d4c-b77a-7358523236d8">

**Comment by VictoriaVVei** [comment]
Example: https://game-recommendation-vic.web.app/help

**Comment by sloaneshea** [comment]
Have some sort of link to games and why you should earn points
