### ISSUE TITLE
Bug Minor: Nav bar not linked in garden page.

### ISSUE THREAD

**Issue by kchoi22** [info442-su23/b-team#84]
Summary: In the garden page, the nav bars are displayed but not clickable.

Environment:  MacOS Google Chrome

steps to reproduce: After selecting the see, I clicked on garden, the nav links are not linked to anywhere.

expected result: Redirection to the other pages. 
actual result: No change is pages.

**Comment by sloaneshea** [comment]
https://github.com/info442-su23/b-team/issues/81#issue-1842289300
