### ISSUE TITLE
Incorrect sort page doesn't render anything.

### ISSUE THREAD

**Issue by kchoi22** [info442-su23/b-team#87]
Summary: In the sorting game feature, after submitting an answer, I can assume that this is supposed to be the incorrect page but since nothing is rendering there are no other indication of whether or not I got the answer right.

Environment: MacOS Google Chrome

steps to reproduce: During the sorting gaming, after submitting an answer, if the answer is incorrect, nothing gets rendered on the page.

expected result: Result page.

actual result: Nothing rendering on the page except for the green background.

**Comment by BrookePedersen** [comment]
https://github.com/info442-su23/b-team/issues/72
