### ISSUE TITLE
Feature request: Add a button in DIY instruction to show the end of 'next step'

### ISSUE THREAD

**Issue by haonanzzz** [info442-su23/b-team#89]
- request to have a button instead of 'next step' at the end of the DIY instruction, which help user avoid looping all the time; may be add a previous step can also be helpful
- It can show the compost intruction is over, or enable users to get back with previous steps easily

**Comment by BrookePedersen** [comment]
not at the top of our priority list, just an added bonus to the app.

**Comment by bonglrob** [comment]
https://github.com/info442-su23/b-team/issues/86
