### ISSUE TITLE
Feature Request: Saving progress on planting

### ISSUE THREAD

**Issue by phyllisUW** [info442-su23/b-team#90]
Login feature or any type of feature that allows user to save progress during use of webpage.
After I complete certain quizzes or plant seeds, I would like a method of saving my progress in any way, maybe with login functions because this seems to be a webpage with lots of opportunities and progression that I would like to come back to.

**Comment by BrookePedersen** [comment]
how to fix: use cookies

**Comment by BrookePedersen** [comment]
we were planning to use cookies, but do not have enough time so a login feature is not needed.
