### ISSUE TITLE
Back button covers text on navigational bar page- feature request

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/b-team#95]
![35320817-BF13-4285-8F17-BE76F146FCB6](https://github.com/info442-su23/b-team/assets/43656152/382e0f14-0020-401a-9634-6ba1ee63d516)

On a mobile device it the back button is covering the text a minor issue. Once fixed it’ll look great. App functions and looks great.

**Comment by bonglrob** [comment]
Work worth doing, won’t be completed in the next sprint:
We will work on this in a future sprint once all major bugs of the game functionality is fixed

**Comment by BrookePedersen** [comment]
how to fix: add a media query

**Comment by BrookePedersen** [comment]
https://github.com/info442-su23/b-team/issues/79
